# Generated by Django 6.0.5 on 2026-05-27 13:47

from django.db import migrations


def create_and_set_authors_to_articles(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    User = apps.get_model('auth', 'User')
    articles = Article.objects.filter(author__isnull=False).exclude(author='')

    for article in articles:
        author, _ = User.objects.get_or_create(username=article.author)
        article.author_obj = author
        article.save()


def rollback(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(articles__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_author_obj'),
    ]

    operations = [
        migrations.RunPython(create_and_set_authors_to_articles, rollback),
    ]
