# Generated by Django 6.0.5 on 2026-06-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20260625_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
