# Generated by Django 6.0.5 on 2026-06-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_obj',
            new_name='author',
        ),
    ]
