# Generated by Django 6.0.5 on 2026-06-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_rename_author_obj_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
