# Generated by Django 6.0.5 on 2026-06-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('сan_have_piece_of_pizza', 'Может съесть кусочек пиццы')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
